### ISSUE TITLE
config.ini, problems with mediafolder (error in'config.ini' [line 10]: 'media\n' 

### ISSUE THREAD

**Issue by deranker1** [corbindavenport/memebot#2]
i have this error about the MediaFolder in the config.ini under [BotSettings] and I'm not sure what I'm doing wrong. Could anyone give me an example what would come after MediaFolder ? Much appriciated.

**Comment by corbindavenport** [comment]
It should just be the name of the folder you want, which is then stored in the same location as the memebot script. This is what I have:

```
[BotSettings]
CacheFile: cache.csv
TwitterUsername: ItMeIRL
MediaFolder: media
DelayBetweenTweets: 600
SubredditToMonitor: me_irl
```

**Comment by deranker1** [comment]
No line break at the end, I tried your example, made the directory at same location as the memebot script and still the same error. Weird..

**Comment by corbindavenport** [comment]
This could be related. https://twitter.com/Grawlix/status/870808609927692288

**Comment by corbindavenport** [comment]
I'm closing this issue, but feel free to re-open it if you're still having issues.
